package github.activity.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WIDGET_SETTINGS.
 */
public class WidgetSettings {

    private Long id;
    private String user;

    public WidgetSettings() {
    }

    public WidgetSettings(Long id) {
        this.id = id;
    }

    public WidgetSettings(Long id, String user) {
        this.id = id;
        this.user = user;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

}
