package github.activity.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import github.activity.dao.DayActivity;
import github.activity.dao.WidgetSettings;

import github.activity.dao.DayActivityDao;
import github.activity.dao.WidgetSettingsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayActivityDaoConfig;
    private final DaoConfig widgetSettingsDaoConfig;

    private final DayActivityDao dayActivityDao;
    private final WidgetSettingsDao widgetSettingsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayActivityDaoConfig = daoConfigMap.get(DayActivityDao.class).clone();
        dayActivityDaoConfig.initIdentityScope(type);

        widgetSettingsDaoConfig = daoConfigMap.get(WidgetSettingsDao.class).clone();
        widgetSettingsDaoConfig.initIdentityScope(type);

        dayActivityDao = new DayActivityDao(dayActivityDaoConfig, this);
        widgetSettingsDao = new WidgetSettingsDao(widgetSettingsDaoConfig, this);

        registerDao(DayActivity.class, dayActivityDao);
        registerDao(WidgetSettings.class, widgetSettingsDao);
    }
    
    public void clear() {
        dayActivityDaoConfig.getIdentityScope().clear();
        widgetSettingsDaoConfig.getIdentityScope().clear();
    }

    public DayActivityDao getDayActivityDao() {
        return dayActivityDao;
    }

    public WidgetSettingsDao getWidgetSettingsDao() {
        return widgetSettingsDao;
    }

}
