package github.activity.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DAY_ACTIVITY.
 */
public class DayActivity {

    private String user;
    private java.util.Date date;
    private Integer count;

    public DayActivity() {
    }

    public DayActivity(String user, java.util.Date date, Integer count) {
        this.user = user;
        this.date = date;
        this.count = count;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
