name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: assemble-debug
        uses: msfjarvis/setup-android@0.2
        with:
          gradleTasks: :app:assembleDebug

      - name: assemble-release
        uses: msfjarvis/setup-android@0.2
        with:
          gradleTasks: :app:assembleRelease
